bumppkg: support rebuilds

diff --git a/bumppkg b/bumppkg
--- a/bumppkg
+++ b/bumppkg
@@ -21,7 +21,7 @@ esac
 _pkgbase=$1
 _pkgver=$2
 _pkgrel=$3
-_msg=$4
+_msg="$4"
 
 _build=1
 
@@ -39,10 +39,10 @@ pushd $_pkgbase/
 
 _pkgname=$(. PKGBUILD; echo $pkgname)
 for _repo in core extra multilib; do
-    if pacman -Sql $_repo | grep "^$_pkgname$" >/dev/null; then
-        _target=$_repo
-        break
-    fi
+  if pacman -Sql $_repo | grep "^$_pkgname$" >/dev/null; then
+    _target=$_repo
+    break
+  fi
 done
 
 if [[ -n "$_suffix" ]]; then
@@ -51,57 +51,64 @@ if [[ -n "$_suffix" ]]; then
 fi
 
 if [[ -z "$_target" ]]; then
-    echo "Cannot find package in x86 repo."
-    exit 1
+  echo "Cannot find package in x86 repo."
+  exit 1
 fi
 
 _oldpkgver=$(. PKGBUILD; echo $pkgver)
 
-if [[ "$_pkgver" != "HEAD" ]]; then
-  setconf PKGBUILD pkgver $_pkgver
-fi
-setconf PKGBUILD pkgrel $_pkgrel
+if [[ "$_pkgver" == "rebuild" ]]; then
+  _rebuild="--rebuild"
+  _msg="$3"
 
-if grep '^_commit=' PKGBUILD >/dev/null; then
-  if [[ -n "$COMMIT" ]]; then
-    setconf PKGBUILD _commit $COMMIT
-  else
-    # Attempt to update _commit
-    _oldcommit=$(. PKGBUILD; echo $_commit)
-    for _source in $(. PKGBUILD; echo ${source[@]}); do
-      if [[ $_source =~ git\+(https://.*)\#commit=$_oldcommit ]]; then
-        _gitrepo=${BASH_REMATCH[1]}
+else
 
-        if [[ $_pkgver == "HEAD" ]]; then
-          _commit="$(git ls-remote $_gitrepo | grep HEAD | cut -f1)"
-        else
-          tags="$(git ls-remote --tags $_gitrepo)"
+  if [[ "$_pkgver" != "head" ]]; then
+    setconf PKGBUILD pkgver $_pkgver
+  fi
+  setconf PKGBUILD pkgrel $_pkgrel
 
-          _guess_tag_prefix=$(echo "$tags" | grep ^$_oldcommit | sed "s|.*refs/tags/||;s|$_oldpkgver.*||" | head -n1)
-          if echo "$tags" | grep refs/tags/$_guess_tag_prefix$_pkgver$ >/dev/null; then
-            _newtag=$_guess_tag_prefix$_pkgver
-          elif echo "$tags" | grep refs/tags/$_pkgver$ >/dev/null; then
-            _newtag=$_pkgver
-          elif echo "$tags" | grep refs/tags/v$_pkgver$ >/dev/null; then
-            _newtag=v$_pkgver
-          elif echo "$tags" | grep refs/tags/V$_pkgver$ >/dev/null; then
-            _newtag=V$_pkgver
+  if grep '^_commit=' PKGBUILD >/dev/null; then
+    if [[ -n "$COMMIT" ]]; then
+      setconf PKGBUILD _commit $COMMIT
+    else
+      # Attempt to update _commit
+      _oldcommit=$(. PKGBUILD; echo $_commit)
+      for _source in $(. PKGBUILD; echo ${source[@]}); do
+        if [[ $_source =~ git\+(https://.*)\#commit=$_oldcommit ]]; then
+          _gitrepo=${BASH_REMATCH[1]}
+
+          if [[ $_pkgver == "HEAD" ]]; then
+            _commit="$(git ls-remote $_gitrepo | grep HEAD | cut -f1)"
           else
-            echo "Unable to find tag for $_pkgver"
-            exit 1
+            tags="$(git ls-remote --tags $_gitrepo)"
+
+            _guess_tag_prefix=$(echo "$tags" | grep ^$_oldcommit | sed "s|.*refs/tags/||;s|$_oldpkgver.*||" | head -n1)
+            if echo "$tags" | grep refs/tags/$_guess_tag_prefix$_pkgver$ >/dev/null; then
+              _newtag=$_guess_tag_prefix$_pkgver
+            elif echo "$tags" | grep refs/tags/$_pkgver$ >/dev/null; then
+              _newtag=$_pkgver
+            elif echo "$tags" | grep refs/tags/v$_pkgver$ >/dev/null; then
+              _newtag=v$_pkgver
+            elif echo "$tags" | grep refs/tags/V$_pkgver$ >/dev/null; then
+              _newtag=V$_pkgver
+            else
+              echo "Unable to find tag for $_pkgver"
+              exit 1
+            fi
+
+            if echo "$tags" | grep $_newtag^{}$ >/dev/null; then
+              _commit=$(echo "$tags" | grep refs/tags/$_newtag^{}$ | cut -f1)
+            else
+              _commit=$(echo "$tags" | grep refs/tags/$_newtag$ | cut -f1)
+            fi
           fi
 
-          if echo "$tags" | grep $_newtag^{}$ >/dev/null; then
-            _commit=$(echo "$tags" | grep refs/tags/$_newtag^{}$ | cut -f1)
-          else
-            _commit=$(echo "$tags" | grep refs/tags/$_newtag$ | cut -f1)
-          fi
+          setconf PKGBUILD _commit $_commit
+          break
         fi
-
-        setconf PKGBUILD _commit $_commit
-        break
-      fi
-    done
+      done
+    fi
   fi
 fi
 
@@ -135,7 +142,7 @@ git --no-pager diff
 if [[ "$_build" -eq 1 ]]; then
   _buildserver=$(felixbuild-server-select)
 
-  felixbuild $_buildserver pkgctl build $_suffix
+  felixbuild $_buildserver pkgctl build $_suffix $_rebuild
 
   BUILDHOST=$_buildserver PKGBASE=$_pkgbase felix-rsync-wrapper pkgctl release $_suffix -m "$_msg"
 
